name: CI Pipeline

on: [push]
  # push:
  #   branches:
  #     - main  # Change to  your default branch if it's not 'main'
  # pull_request:
  #   branches:
  #     - main  # Change to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r attendance/requirements.txt  # Make sure you have a requirements.txt file
          pip install pytest 

      - name: Run tests
        run: |
          cd attendance
          python -m pytest test_attendance_api.py

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          cd attendance
          # docker build . --file Dockerfile --tag attendance_api:latest
          docker build -t my-app .
          
      - name: List Docker Images
        run: docker images
        
      - name: Push Docker Image
        run: |
          docker tag my-app subhan0807/my-app:latest
          docker push subhan0807/my-app:latest

          
      # - name: Deploy (optional)
      #   run: |
      #     # Add your deployment commands here
      #     # For example, using SSH to a remote server
