name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r attendance/requirements.txt
          pip install pytest 

      - name: Run tests
        run: |
          cd attendance
          python -m pytest test_attendance_api.py

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Define Image Tag
        id: vars
        run: |
          echo "TAG=${GITHUB_SHA:0:7}" >> $GITHUB_ENV  # Use the short SHA for tagging
          # Alternatively, you could use a version number or timestamp
          # echo "TAG=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          cd attendance
          docker build -t my-app:${{ env.TAG }} .

      - name: List Docker Images
        run: docker images

      - name: Push Docker Image
        run: |
          docker tag my-app:${{ env.TAG }} subhan0807/my-app:${{ env.TAG }}
          docker push subhan0807/my-app:${{ env.TAG }}
